name: Download Bing Wallpaper
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Bing Wallpaper
        run: |
          # 使用curl命令下载壁纸
          # 注意：这里使用的是必应壁纸的API URL，但出于保护目的，这里不直接给出
          # 你需要自行查找或编写脚本来获取每日壁纸的URL
          URL=https://cn.bing.com"$(curl -s 'https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN' | jq -r '.images[0].url')"
          wget -O ./bing-wallpaper.jpg $URL
      - name: Configurate git
        run: |
          # 提交更改到GitHub
          git config --local user.name "Xunhaii"
          git config --local user.email "102942357+Xunhaii@users.noreply.github.com"
          git add bing-wallpaper.jpg
          git commit -m "更新Bing壁纸"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
